#Part A code
install.packages(“ISwR”)
library("ISwR")
setwd("~/Desktop")
iv<-read.csv("354111_IV.csv")
dv<-read.csv("354111_DV.csv")
merge_data<-merge(iv,dv,by="ID",all=TRUE)
str(merge_data)
any(is.na(merge_data[,2])==TRUE)
any(is.nan(PartA[,2])==TRUE)
any(is.na(PartA[,3]) == TRUE) 
any(is.nan(PartA[,3]) == TRUE)
incomplete_data<-merge_data
library(mice)
md.pattern(incomplete_data)
A_imp<-merge_data[!is.na(merge_data$IV)==TRUE|!is.na(merge_data$DV)==TRUE,]
imp<-mice(A_imp, method=”norm.boot”, printFlag=FALSE)
A_Complete<-complete(imp)
md.pattern(A_complete)
M<-lm(DV~IV, data=A_complete)
summary(M)
library(knitr)
kable(anova(M), caption= ‘ANOVA Table’)
plot(A_complete$DV ~ A_complete$IV, main='Scatter : DV ~ IV', xlab='IV', ylab='DV', pch=20)
abline(M, col='red', lty=3, lwd=2)
legend('topleft', legend='Estimated Regression Line', lty=3, lwd=2, col='red')
confint(M, level = 0.95)
confint(M, level = 0.99)
