#Part B code
setwd("~/Desktop")
PartB<-read.csv("354111_PartB.csv")
origin<-lm(I(y)~I(x),data=PartB)
summary(origin)
plot(PartB$y~PartB$x, main= ‘Scatter:y~x’, xlab=x,ylab=y,pch=20)
abline(origin,col='red', lty=3, lwd=2)
legend('topleft', legend='Estimated Regression Line', lty=3, lwd=2, col='red')
B1<-lm(I(y)~I(x^(-1)),data=PartB)
summary(B1)
B2<-lm(I(y)~I(x^(1/2)),data=PartB)
summary(B2)
B3<-lm(I(y)~I(x^(-1/2)),data=PartB)
summary(B3)
B4<-lm(I(y)~I(x^(2)),data=PartB)
summary(B4)
B5<-lm(I(y)~I(log(x)),data=PartB)
summary(B5)
B6<-lm(I(y^(-1))~I(x),data=PartB)
summary(B6)
B7<-lm(I(y^(-1))~I(x^(-1)),data=PartB)
summary(B7)
B8<-lm(I(y^(-1))~I(x^(-1/2)),data=PartB)
summary(B8)
B9<-lm(I(y^(-1))~I(x^(1/2)),data=PartB)
summary(B9)
B10<-lm(I(y^(-1))~I(x^(2)),data=PartB)
summary(B10)
B11<-lm(I(y^(-1))~I(log(x)),data=PartB)
summary(B11)
B12<-lm(I(y^(-1/2))~I(x),data=PartB)
summary(B12)
B13<-lm(I(y^(-1/2))~I(x^(-1)),data=PartB)
summary(B13)
B14<-lm(I(y^(-1/2))~I(x^(-1/2)),data=PartB)
summary(B14)
B15<-lm(I(y^(-1/2))~I(x^(1/2)),data=PartB)
summary(B15)
B16<-lm(I(y^(-1/2))~I(x^(2)),data=PartB)
summary(B16)
B17<-lm(I(y^(-1/2))~I(log(x)),data=PartB)
summary(B17)
B18<-lm(I(y^(1/2))~I(x),data=PartB)
summary(B18)
B19<-lm(I(y^(1/2))~I(x^(-1)),data=PartB)
summary(B19)
B20<-lm(I(y^(1/2))~I(x^(-½)),data=PartB)
summary(B20)
B21<-lm(I(y^(1/2))~I(x^(½)),data=PartB)
summary(B21)
B22<-lm(I(y^(1/2))~I(x^(2)),data=PartB))
summary(B22)
B23<-lm(I(y^(1/2))~I(log(x)),data=PartB)
summary(B23)
B24<-lm(I(y^(2))~I(x),data=PartB)
summary(B24)
B25<-lm(I(y^(2))~I(x^(-1)),data=PartB)
summary(B25)
B26<-lm(I(y^(2))~I(x^(-1/2)),data=PartB)
summary(B26)
B27<-lm(I(y^(2))~I(x^(1/2)),data=PartB)
summary(B27)
B28<-lm(I(y^(2))~I(x^(2)),data=PartB)
summary(B28)
B29<-lm(I(y^(2))~I(log(x)),data=PartB)
summary(B29)
B30<-lm(I(log(y))~I(x),data=PartB)
summary(B30)
B31<-lm(I(log(y))~I(x^(-1)),data=PartB)
summary(B31)
B32<-lm(I(log(y))~I(x^(-1/2)),data=PartB)
summary(B32)
B33<-lm(I(log(y))~I(x^(1/2)),data=PartB)
summary(B33)
B34<-lm(I(log(y))~I(x^(2)),data=PartB)
summary(B34)
B35<-lm(I(log(y))~I(log(x)),data=PartB)
summary(B35)
plot(PartB$y^(2)~PartB$x, main='Scatter:y~x’,xlab=x,ylab=y,pch=20)
abline(B24,col= ‘red’, lty=3, lwd=2)
legend('topleft', legend='Estimated Regression Line', lty=3, lwd=2, col='red')
data_trans <- data.frame(xtrans=data$x, ytrans=data$y^(2))
groups <- cut(data_trans$xtrans,breaks=c(-Inf,seq(min(data_trans$xtrans)+0.3, max(data_trans$xtrans)-0.3,by=0.3),Inf))
table(groups)
x <- ave(data_trans$xtrans, groups)
data_bin <- data.frame(x=x, y=data_trans$ytrans)
install.packages('olsrr')
library("olsrr")
fit_b<-lm(y~x,data=data_bin)
ols_pure_error_anova(fit_b)
fit_b_final <- lm(ytrans ~ xtrans, data = data_trans)
summary(fit_b_final)
